
patient_metadata: "/Users/.../config/metadata.csv"

input_dir: "/Users/../input"

output_dir: "/Users/../output"

log_dir: "/Users/../logs"

genome: "/Users/../hg19_genome/hg19.fa"

average_target_size: 10000

annotation: "/Users/../refFlat.txt"

threads: 12
